"""add evento

Revision ID: 3c2b6717d491
Revises: 53b6c571cacb
Create Date: 2026-07-22 16:40:55.448568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3c2b6717d491'
down_revision: Union[str, None] = '53b6c571cacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_evento')
    )
    op.create_index(op.f('ix_evento_fecha_inicio'), 'evento', ['fecha_inicio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evento_fecha_inicio'), table_name='evento')
    op.drop_table('evento')
    # ### end Alembic commands ###
