"""add asistencia

Revision ID: 44afaca4d211
Revises: 87e73f257516
Create Date: 2026-07-21 17:51:45.443880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44afaca4d211'
down_revision: Union[str, None] = '87e73f257516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencia',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupo.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_asistencia'),
    sa.UniqueConstraint('id_estudiante', 'id_grupo', 'fecha', name='uq_asistencia')
    )
    op.create_index(op.f('ix_asistencia_fecha'), 'asistencia', ['fecha'], unique=False)
    op.create_index(op.f('ix_asistencia_id_estudiante'), 'asistencia', ['id_estudiante'], unique=False)
    op.create_index(op.f('ix_asistencia_id_grupo'), 'asistencia', ['id_grupo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencia_id_grupo'), table_name='asistencia')
    op.drop_index(op.f('ix_asistencia_id_estudiante'), table_name='asistencia')
    op.drop_index(op.f('ix_asistencia_fecha'), table_name='asistencia')
    op.drop_table('asistencia')
    # ### end Alembic commands ###
