"""add comunicado

Revision ID: 53b6c571cacb
Revises: 9e08fb40ed2b
Create Date: 2026-07-22 16:20:33.882471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53b6c571cacb'
down_revision: Union[str, None] = '9e08fb40ed2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicado',
    sa.Column('id_comunicado', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('dirigido_a', sa.String(length=20), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_comunicado')
    )
    op.create_index(op.f('ix_comunicado_dirigido_a'), 'comunicado', ['dirigido_a'], unique=False)
    op.create_index(op.f('ix_comunicado_fecha_publicacion'), 'comunicado', ['fecha_publicacion'], unique=False)
    op.create_index(op.f('ix_comunicado_id_autor'), 'comunicado', ['id_autor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comunicado_id_autor'), table_name='comunicado')
    op.drop_index(op.f('ix_comunicado_fecha_publicacion'), table_name='comunicado')
    op.drop_index(op.f('ix_comunicado_dirigido_a'), table_name='comunicado')
    op.drop_table('comunicado')
    # ### end Alembic commands ###
