"""add encargado and encargado_estudiante

Revision ID: 87e73f257516
Revises: 8e33f5d0d8d3
Create Date: 2026-07-21 02:33:11.764786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87e73f257516'
down_revision: Union[str, None] = '8e33f5d0d8d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encargado',
    sa.Column('id_encargado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('name_encargado', sa.String(length=100), nullable=False),
    sa.Column('sec_name_encargado', sa.String(length=100), nullable=False),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('num_documento_encargado', sa.String(length=30), nullable=False),
    sa.Column('phone_num_encargado', sa.String(length=20), nullable=True),
    sa.Column('direction_encargado', sa.String(length=255), nullable=True),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipo_documento.id_tipo_documento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_encargado'),
    sa.UniqueConstraint('num_documento_encargado')
    )
    op.create_index(op.f('ix_encargado_id_tipo_documento'), 'encargado', ['id_tipo_documento'], unique=False)
    op.create_index(op.f('ix_encargado_id_usuario'), 'encargado', ['id_usuario'], unique=True)
    op.create_table('encargado_estudiante',
    sa.Column('id_encargado_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_encargado', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_encargado'], ['encargado.id_encargado'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.PrimaryKeyConstraint('id_encargado_estudiante'),
    sa.UniqueConstraint('id_encargado', 'id_estudiante', name='uq_encargado_estudiante')
    )
    op.create_index(op.f('ix_encargado_estudiante_id_encargado'), 'encargado_estudiante', ['id_encargado'], unique=False)
    op.create_index(op.f('ix_encargado_estudiante_id_estudiante'), 'encargado_estudiante', ['id_estudiante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encargado_estudiante_id_estudiante'), table_name='encargado_estudiante')
    op.drop_index(op.f('ix_encargado_estudiante_id_encargado'), table_name='encargado_estudiante')
    op.drop_table('encargado_estudiante')
    op.drop_index(op.f('ix_encargado_id_usuario'), table_name='encargado')
    op.drop_index(op.f('ix_encargado_id_tipo_documento'), table_name='encargado')
    op.drop_table('encargado')
    # ### end Alembic commands ###
