"""initial schema

Revision ID: 8e33f5d0d8d3
Revises: 
Create Date: 2026-07-17 20:18:33.903649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e33f5d0d8d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignatura',
    sa.Column('id_asignatura', sa.Integer(), nullable=False),
    sa.Column('name_asignatura', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_asignatura'),
    sa.UniqueConstraint('name_asignatura')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('name_rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('name_rol')
    )
    op.create_table('tipo_documento',
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('name_tipo_documento', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_documento'),
    sa.UniqueConstraint('name_tipo_documento')
    )
    op.create_table('grupo',
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('name_grupo', sa.String(length=100), nullable=False),
    sa.Column('id_asignatura', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_asignatura'], ['asignatura.id_asignatura'], ),
    sa.PrimaryKeyConstraint('id_grupo')
    )
    op.create_index(op.f('ix_grupo_id_asignatura'), 'grupo', ['id_asignatura'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('correo_institucional', sa.String(length=150), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_correo_institucional'), 'usuario', ['correo_institucional'], unique=True)
    op.create_index(op.f('ix_usuario_id_rol'), 'usuario', ['id_rol'], unique=False)
    op.create_table('estudiante',
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('name_estudiante', sa.String(length=100), nullable=False),
    sa.Column('sec_name_estudiante', sa.String(length=100), nullable=False),
    sa.Column('birthdate_estudiante', sa.Date(), nullable=False),
    sa.Column('direction_estudiante', sa.String(length=255), nullable=True),
    sa.Column('phone_num_estudiante', sa.String(length=20), nullable=True),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('num_documento_estudiante', sa.String(length=30), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupo.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipo_documento.id_tipo_documento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_estudiante'),
    sa.UniqueConstraint('num_documento_estudiante')
    )
    op.create_index(op.f('ix_estudiante_id_grupo'), 'estudiante', ['id_grupo'], unique=False)
    op.create_index(op.f('ix_estudiante_id_tipo_documento'), 'estudiante', ['id_tipo_documento'], unique=False)
    op.create_index(op.f('ix_estudiante_id_usuario'), 'estudiante', ['id_usuario'], unique=True)
    op.create_table('profesor',
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('name_profesor', sa.String(length=100), nullable=False),
    sa.Column('sec_name_profesor', sa.String(length=100), nullable=False),
    sa.Column('birthdate_profesor', sa.Date(), nullable=False),
    sa.Column('direction_profesor', sa.String(length=255), nullable=True),
    sa.Column('phone_num_profesor', sa.String(length=20), nullable=True),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('num_documento_profesor', sa.String(length=30), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupo.id_grupo'], ),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipo_documento.id_tipo_documento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_profesor'),
    sa.UniqueConstraint('num_documento_profesor')
    )
    op.create_index(op.f('ix_profesor_id_grupo'), 'profesor', ['id_grupo'], unique=False)
    op.create_index(op.f('ix_profesor_id_tipo_documento'), 'profesor', ['id_tipo_documento'], unique=False)
    op.create_index(op.f('ix_profesor_id_usuario'), 'profesor', ['id_usuario'], unique=True)
    op.create_table('subgrupo',
    sa.Column('id_subgrupo', sa.Integer(), nullable=False),
    sa.Column('name_subgrupo', sa.String(length=100), nullable=False),
    sa.Column('tipo_subgrupo', sa.String(length=50), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupo.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_subgrupo')
    )
    op.create_index(op.f('ix_subgrupo_id_grupo'), 'subgrupo', ['id_grupo'], unique=False)
    op.create_table('subgrupo_estudiante',
    sa.Column('id_subgrupo_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('id_subgrupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_subgrupo'], ['subgrupo.id_subgrupo'], ),
    sa.PrimaryKeyConstraint('id_subgrupo_estudiante'),
    sa.UniqueConstraint('id_estudiante', 'id_subgrupo', name='uq_subgrupo_estudiante')
    )
    op.create_index(op.f('ix_subgrupo_estudiante_id_estudiante'), 'subgrupo_estudiante', ['id_estudiante'], unique=False)
    op.create_index(op.f('ix_subgrupo_estudiante_id_subgrupo'), 'subgrupo_estudiante', ['id_subgrupo'], unique=False)
    op.create_table('subgrupo_profesor',
    sa.Column('id_subgrupo_profesor', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=False),
    sa.Column('id_subgrupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_profesor'], ['profesor.id_profesor'], ),
    sa.ForeignKeyConstraint(['id_subgrupo'], ['subgrupo.id_subgrupo'], ),
    sa.PrimaryKeyConstraint('id_subgrupo_profesor'),
    sa.UniqueConstraint('id_profesor', 'id_subgrupo', name='uq_subgrupo_profesor')
    )
    op.create_index(op.f('ix_subgrupo_profesor_id_profesor'), 'subgrupo_profesor', ['id_profesor'], unique=False)
    op.create_index(op.f('ix_subgrupo_profesor_id_subgrupo'), 'subgrupo_profesor', ['id_subgrupo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subgrupo_profesor_id_subgrupo'), table_name='subgrupo_profesor')
    op.drop_index(op.f('ix_subgrupo_profesor_id_profesor'), table_name='subgrupo_profesor')
    op.drop_table('subgrupo_profesor')
    op.drop_index(op.f('ix_subgrupo_estudiante_id_subgrupo'), table_name='subgrupo_estudiante')
    op.drop_index(op.f('ix_subgrupo_estudiante_id_estudiante'), table_name='subgrupo_estudiante')
    op.drop_table('subgrupo_estudiante')
    op.drop_index(op.f('ix_subgrupo_id_grupo'), table_name='subgrupo')
    op.drop_table('subgrupo')
    op.drop_index(op.f('ix_profesor_id_usuario'), table_name='profesor')
    op.drop_index(op.f('ix_profesor_id_tipo_documento'), table_name='profesor')
    op.drop_index(op.f('ix_profesor_id_grupo'), table_name='profesor')
    op.drop_table('profesor')
    op.drop_index(op.f('ix_estudiante_id_usuario'), table_name='estudiante')
    op.drop_index(op.f('ix_estudiante_id_tipo_documento'), table_name='estudiante')
    op.drop_index(op.f('ix_estudiante_id_grupo'), table_name='estudiante')
    op.drop_table('estudiante')
    op.drop_index(op.f('ix_usuario_id_rol'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo_institucional'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_grupo_id_asignatura'), table_name='grupo')
    op.drop_table('grupo')
    op.drop_table('tipo_documento')
    op.drop_table('rol')
    op.drop_table('asignatura')
    # ### end Alembic commands ###
