"""add administrativo

Revision ID: 9e08fb40ed2b
Revises: b7d164a21c7d
Create Date: 2026-07-22 04:24:20.283809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e08fb40ed2b'
down_revision: Union[str, None] = 'b7d164a21c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrativo',
    sa.Column('id_administrativo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('name_administrativo', sa.String(length=100), nullable=False),
    sa.Column('sec_name_administrativo', sa.String(length=100), nullable=False),
    sa.Column('id_tipo_documento', sa.Integer(), nullable=False),
    sa.Column('num_documento_administrativo', sa.String(length=30), nullable=False),
    sa.Column('phone_num_administrativo', sa.String(length=20), nullable=True),
    sa.Column('direction_administrativo', sa.String(length=255), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_tipo_documento'], ['tipo_documento.id_tipo_documento'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_administrativo'),
    sa.UniqueConstraint('num_documento_administrativo')
    )
    op.create_index(op.f('ix_administrativo_id_tipo_documento'), 'administrativo', ['id_tipo_documento'], unique=False)
    op.create_index(op.f('ix_administrativo_id_usuario'), 'administrativo', ['id_usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_administrativo_id_usuario'), table_name='administrativo')
    op.drop_index(op.f('ix_administrativo_id_tipo_documento'), table_name='administrativo')
    op.drop_table('administrativo')
    # ### end Alembic commands ###
