"""add evaluacion and nota

Revision ID: b7d164a21c7d
Revises: 44afaca4d211
Create Date: 2026-07-21 18:13:06.191433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7d164a21c7d'
down_revision: Union[str, None] = '44afaca4d211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluacion',
    sa.Column('id_evaluacion', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.Integer(), nullable=False),
    sa.Column('name_evaluacion', sa.String(length=100), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_grupo'], ['grupo.id_grupo'], ),
    sa.PrimaryKeyConstraint('id_evaluacion')
    )
    op.create_index(op.f('ix_evaluacion_id_grupo'), 'evaluacion', ['id_grupo'], unique=False)
    op.create_table('nota',
    sa.Column('id_nota', sa.Integer(), nullable=False),
    sa.Column('id_evaluacion', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_estudiante'], ['estudiante.id_estudiante'], ),
    sa.ForeignKeyConstraint(['id_evaluacion'], ['evaluacion.id_evaluacion'], ),
    sa.PrimaryKeyConstraint('id_nota'),
    sa.UniqueConstraint('id_evaluacion', 'id_estudiante', name='uq_nota')
    )
    op.create_index(op.f('ix_nota_id_estudiante'), 'nota', ['id_estudiante'], unique=False)
    op.create_index(op.f('ix_nota_id_evaluacion'), 'nota', ['id_evaluacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nota_id_evaluacion'), table_name='nota')
    op.drop_index(op.f('ix_nota_id_estudiante'), table_name='nota')
    op.drop_table('nota')
    op.drop_index(op.f('ix_evaluacion_id_grupo'), table_name='evaluacion')
    op.drop_table('evaluacion')
    # ### end Alembic commands ###
